[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "cerebras>=0.0.1",
    "fastapi>=0.121.0",
    "langchain>=0.3.27",
    "langchain-cerebras>=0.5.0",
    "python-dotenv>=1.2.1",
    "uvicorn>=0.38.0",
]
